package com.weldrite.app.ui.theme

import androidx.compose.ui.graphics.Color

// Brand palette extracted from weldrite.in
val BrandMaroon = Color(0xFF8D3132)
val BrandRed = Color(0xFFFF131D)
val BrandCharcoal = Color(0xFF32373C)

// Light scheme
val md_primary = Color(0xFF8D3132)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFFFDAD6)
val md_onPrimaryContainer = Color(0xFF3B0808)
val md_secondary = Color(0xFF775653)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFFFDAD6)
val md_onSecondaryContainer = Color(0xFF2C1513)
val md_tertiary = Color(0xFFC8102E)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFFFDAD7)
val md_onTertiaryContainer = Color(0xFF40000A)
val md_background = Color(0xFFFFF8F7)
val md_onBackground = Color(0xFF201A1A)
val md_surface = Color(0xFFFFFFFF)
val md_onSurface = Color(0xFF201A1A)
val md_surfaceVariant = Color(0xFFF5DDDB)
val md_onSurfaceVariant = Color(0xFF534341)
val md_outline = Color(0xFF857371)
val md_outlineVariant = Color(0xFFD8C2BF)
val md_error = Color(0xFFBA1A1A)
val md_onError = Color(0xFFFFFFFF)
val md_surfaceContainer = Color(0xFFFCEEEC)

// Dark scheme
val md_dark_primary = Color(0xFFFFB3AD)
val md_dark_onPrimary = Color(0xFF571D1D)
val md_dark_primaryContainer = Color(0xFF73332F)
val md_dark_onPrimaryContainer = Color(0xFFFFDAD6)
val md_dark_secondary = Color(0xFFE7BDB8)
val md_dark_onSecondary = Color(0xFF442927)
val md_dark_secondaryContainer = Color(0xFF5D3F3C)
val md_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val md_dark_tertiary = Color(0xFFFFB3B0)
val md_dark_onTertiary = Color(0xFF5F1019)
val md_dark_tertiaryContainer = Color(0xFF7E2A30)
val md_dark_onTertiaryContainer = Color(0xFFFFDAD7)
val md_dark_background = Color(0xFF1A1110)
val md_dark_onBackground = Color(0xFFECE0DE)
val md_dark_surface = Color(0xFF1A1110)
val md_dark_onSurface = Color(0xFFECE0DE)
val md_dark_surfaceVariant = Color(0xFF534341)
val md_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val md_dark_outline = Color(0xFFA08C8A)
val md_dark_outlineVariant = Color(0xFF534341)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_surfaceContainer = Color(0xFF271D1C)
